In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:

os.getcwd()

'c:\\Users\\Swath\\Desktop\\game dev\\.vscode\\Movie recommendation system'

In [3]:
movie_data = pd.read_csv('movies.csv')
movie_data

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [4]:
#index, homepage, id, overview, original_title, release_date, overview, runtime, crew, vote_average, production_company, production_country, spoken_language and vote_count not needed to find order of recommendations
movie_data = movie_data.drop(['homepage','id','original_title','release_date', 'overview', 'index', 'runtime', 'vote_count', 'crew', 'vote_average', 'production_companies', 'production_countries', 'spoken_languages'], axis=1)
movie_data

,budget,genres,keywords,original_language,popularity,revenue,status,tagline,title,cast,director
0,237000000,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,en,150.437577,2787965087,Released,Enter the World of Pandora.,Avatar,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,300000000,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,en,139.082615,961000000,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski
2,245000000,Action Adventure Crime,spy based on novel secret agent sequel mi6,en,107.376788,880674609,Released,A Plan No One Escapes,Spectre,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes
3,250000000,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,en,112.312950,1084939099,Released,The Legend Ends,The Dark Knight Rises,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan
4,260000000,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,en,43.926995,284139100,Released,"Lost in our world, found in another.",John Carter,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,Action Crime Thriller,united states\u2013mexico barrier legs arms pa...,es,14.269792,2040920,Released,"He didn't come looking for trouble, but troubl...",El Mariachi,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,Robert Rodriguez
4799,9000,Comedy Romance,NaN,en,0.642552,0,Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,Edward Burns
4800,0,Comedy Drama Romance TV Movie,date love at first sight narration investigati...,en,1.444476,0,Released,NaN,"Signed, Sealed, Delivered",Eric Mabius Kristin Booth Crystal Lowe Geoff G...,Scott Smith
4801,0,NaN,NaN,en,0.857008,0,Released,A New Yorker in Shanghai,Shanghai Calling,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,Daniel Hsia
4802,0,Documentary,obsession camcorder crush dream girl,en,1.929883,0,Released,NaN,My Date with Drew,Drew Barrymore Brian Herzlinger Corey Feldman ...,Brian Herzlinger

In [5]:
'''1|if a movie is entered as input then the features whose matching will determine order of recommendationa are:
        1.keywords
        2.genres
        3.original language
        4.cast
        5.director
        6.status
        7.tagline
'''
'''2|After the matching ordering must be done such that the movie with higher:
        1.Profit
        2.Popularity
   comes first.
   
   There there are three steps to find 
'''
#pre-processing genres, keywords and cast
genres = np.array(movie_data['genres'])
for i in range(len(genres)):
    if(type(genres[i])==float):
        genres[i]=[]
        continue
    genres[i]=genres[i].split()

keywords = np.array(movie_data['keywords'])
for i in range(len(keywords)):
    if(type(keywords[i])==float):
        keywords[i]=[]
        continue
    keywords[i]=keywords[i].split()

cast = np.array(movie_data['cast'])
for i in range(len(keywords)):
    if(type(cast[i])==float):
        cast[i]=[]
        continue
    cast[i] = cast[i].split()

title_components = np.array(movie_data['title'])
for i in range(len(keywords)):
    if(type(cast[i])==float):
        title_components[i]=[]
        continue
    title_components[i] = title_components[i].split()

In [6]:
mod_data = pd.DataFrame()
mod_data['genres'] = genres
mod_data['keywords'] = keywords
mod_data['tagline'] = movie_data['tagline']
mod_data['original_language'] =  movie_data['original_language']
mod_data['status'] = movie_data['status']
mod_data['cast'] = cast
mod_data['director'] = movie_data['director']
mod_data['Profit'] = movie_data['revenue']-movie_data['budget']
mod_data['popularity'] = (movie_data['popularity']-movie_data['popularity'].min())/( movie_data['popularity'].max()-movie_data['popularity'].min())
mod_data['title'] = movie_data['title']

mod_data

,genres,keywords,tagline,original_language,status,cast,director,Profit,popularity,title
0,"[Action, Adventure, Fantasy, Science, Fiction]","[culture, clash, future, space, war, space, co...",Enter the World of Pandora.,en,Released,"[Sam, Worthington, Zoe, Saldana, Sigourney, We...",James Cameron,2550965087,0.171815,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...","At the end of the world, the adventure begins.",en,Released,"[Johnny, Depp, Orlando, Bloom, Keira, Knightle...",Gore Verbinski,661000000,0.158846,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...",A Plan No One Escapes,en,Released,"[Daniel, Craig, Christoph, Waltz, L\u00e9a, Se...",Sam Mendes,635674609,0.122635,Spectre
3,"[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...",The Legend Ends,en,Released,"[Christian, Bale, Michael, Caine, Gary, Oldman...",Christopher Nolan,834939099,0.128272,The Dark Knight Rises
4,"[Action, Adventure, Science, Fiction]","[based, on, novel, mars, medallion, space, tra...","Lost in our world, found in another.",en,Released,"[Taylor, Kitsch, Lynn, Collins, Samantha, Mort...",Andrew Stanton,24139100,0.050169,John Carter
...,...,...,...,...,...,...,...,...,...,...
4798,"[Action, Crime, Thriller]","[united, states\u2013mexico, barrier, legs, ar...","He didn't come looking for trouble, but troubl...",es,Released,"[Carlos, Gallardo, Jaime, de, Hoyos, Peter, Ma...",Robert Rodriguez,1820920,0.016298,El Mariachi
4799,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,en,Released,"[Edward, Burns, Kerry, Bish\u00e9, Marsha, Die...",Edward Burns,-9000,0.000734,Newlyweds
4800,"[Comedy, Drama, Romance, TV, Movie]","[date, love, at, first, sight, narration, inve...",NaN,en,Released,"[Eric, Mabius, Kristin, Booth, Crystal, Lowe, ...",Scott Smith,0,0.001650,"Signed, Sealed, Delivered"
4801,[],[],A New Yorker in Shanghai,en,Released,"[Daniel, Henney, Eliza, Coupe, Bill, Paxton, A...",Daniel Hsia,0,0.000979,Shanghai Calling
4802,[Documentary],"[obsession, camcorder, crush, dream, girl]",NaN,en,Released,"[Drew, Barrymore, Brian, Herzlinger, Corey, Fe...",Brian Herzlinger,0,0.002204,My Date with Drew

In [7]:
selection = input("Enter Movie Name ")

In [8]:
genre_interest = mod_data[mod_data['title']==selection].iloc[0,0]
l = len(genres)
genre_score = np.zeros(l)
for i in range(l):
    count = 0
    genre_check = mod_data.iloc[i,0]
    for j in genre_check:
        if j in genre_interest:
            count+=1
    genre_score[i] = count/len(genre_interest)
print(genre_score)

[1.  0.5 0.5 ... 0.  0.  0. ]

In [9]:
keywords_interest = mod_data[mod_data['title']==selection].iloc[0,1]
keywords_score = np.zeros(l)
for i in range(l):
    count = 0
    keywords_check = mod_data.iloc[i,1]
    for j in keywords_check:
        if j in keywords_interest:
            count+=1
    keywords_score[i] = count/len(keywords_interest)
print(keywords_score)

[0.    0.125 0.    ... 0.    0.    0.   ]

In [10]:
original_language_interest = mod_data[mod_data['title']==selection].iloc[0,3]
original_language_score = np.zeros(l)
for i in range(l):
    if (original_language_interest == mod_data.iloc[i,3]):
        original_language_score[i] = 1
print(original_language_score)

[1. 1. 1. ... 1. 1. 1.]

In [11]:
status_interest = mod_data[mod_data['title']==selection].iloc[0,4]
status_score = np.zeros(l)
for i in range(l):
    if (status_interest == mod_data.iloc[i,4]):
        status_score[i] = 1
print(status_score)

[1. 1. 1. ... 1. 1. 1.]

In [12]:
cast_interest = mod_data[mod_data['title']==selection].iloc[0,5]
cast_score = np.zeros(l)
for i in range(l):
    count = 0
    cast_check = mod_data.iloc[i,5]
    for j in cast_check:
        if j in cast_interest:
            count+=1
    cast_score[i] = count/len(cast_interest)
print(cast_score)

[0. 0. 0. ... 0. 0. 0.]

In [13]:
tagline_interest = mod_data[mod_data['title']==selection].iloc[0,2]
tagline_score = np.zeros(l)
for i in range(l):
    if (tagline_interest == mod_data.iloc[i,2]):
        tagline_score[i] = 1
        print(i)
print(tagline_score)

68
[0. 0. 0. ... 0. 0. 0.]

In [14]:
director_interest = mod_data[mod_data['title']==selection].iloc[0,6]
director_score = np.zeros(l)
for i in range(l):
    if (director_interest == mod_data.iloc[i,6]):
        director_score[i] = 1
print(director_score)

[0. 0. 0. ... 0. 0. 0.]

In [15]:
title_interest = mod_data[mod_data['title']==selection].iloc[0,9]
title_score = np.zeros(l)
for i in range(l):
    if(mod_data.iloc[i,9][-1].isdigit() and title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9][:-1] == title_interest[:-1]):
            title_score[i] = 1
    elif(mod_data.iloc[i,9][-1].isdigit() and not title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9][:-2] == title_interest):
            title_score[i] = 1
    elif(not mod_data.iloc[i,9][-1].isdigit() and title_interest[-1].isdigit()):
        if (mod_data.iloc[i,9] == title_interest[:-2]):
            title_score[i] = 1
print(title_score)

[0. 0. 0. ... 0. 0. 0.]

In [16]:
mod_data_2 = pd.DataFrame()
mod_data_2['title'] = mod_data['title']
mod_data_2['tagline_score'] = tagline_score
mod_data_2['keywords_score'] = keywords_score
mod_data_2['genre_score'] = genre_score
mod_data_2['original_language_score'] = original_language_score
mod_data_2['status_score'] = status_score
mod_data_2['cast_score'] = cast_score
mod_data_2['director_score'] = director_score
mod_data_2['popularity'] = mod_data['popularity']
mod_data_2['success_of_movie'] = (mod_data['Profit']-mod_data['Profit'].min())/( mod_data['Profit'].max()-mod_data['Profit'].min())
mod_data_2['title_score'] = title_score
mod_data_2['overall_score'] = mod_data_2['keywords_score']*350 + mod_data_2['genre_score']*300+mod_data_2['director_score']*200+mod_data_2['cast_score']*250+mod_data_2['tagline_score']*10000+mod_data_2['original_language_score']*50+mod_data_2['status_score']*30+mod_data_2['popularity']*150+mod_data_2['success_of_movie']*100+mod_data_2['title_score']*1000
# tagline_score>title_score>keyword_score>genre_score>cast_score>director_score>popularity>success_of_movie>original_languge_score>status_score is the weightage order
mod_data_2

,title,tagline_score,keywords_score,genre_score,original_language_score,status_score,cast_score,director_score,popularity,success_of_movie,title_score,overall_score
0,Avatar,0.0,0.000,1.00,1.0,1.0,0.0,0.0,0.171815,1.000000,0.0,505.772177
1,Pirates of the Caribbean: At World's End,0.0,0.125,0.50,1.0,1.0,0.0,0.0,0.158846,0.304310,0.0,328.007856
2,Spectre,0.0,0.000,0.50,1.0,1.0,0.0,0.0,0.122635,0.294987,0.0,277.893959
3,The Dark Knight Rises,0.0,0.000,0.25,1.0,1.0,0.0,0.0,0.128272,0.368336,0.0,211.074463
4,John Carter,0.0,0.000,1.00,1.0,1.0,0.0,0.0,0.050169,0.069883,0.0,394.513634
...,...,...,...,...,...,...,...,...,...,...,...,...
4798,El Mariachi,0.0,0.125,0.25,0.0,1.0,0.0,0.0,0.016298,0.061668,0.0,157.361392
4799,Newlyweds,0.0,0.000,0.00,1.0,1.0,0.0,0.0,0.000734,0.060994,0.0,86.209486
4800,"Signed, Sealed, Delivered",0.0,0.000,0.00,1.0,1.0,0.0,0.0,0.001650,0.060997,0.0,86.347199
4801,Shanghai Calling,0.0,0.000,0.00,1.0,1.0,0.0,0.0,0.000979,0.060997,0.0,86.246557
4802,My Date with Drew,0.0,0.000,0.00,1.0,1.0,0.0,0.0,0.002204,0.060997,0.0,86.430356

In [17]:
pref_order = np.array(mod_data_2.iloc[:,-1]).argsort()[::-1]
mod_data_2[mod_data_2['title']=='Iron Man 2']
st = 'Iron Man 2'
st[-1].isdigit()

True

In [18]:
print("The movies recommended: \n")
for i in range(30):
    print(mod_data_2.iloc[pref_order[i],0])

The movies recommended:

Iron Man
Iron Man 2
Iron Man 3
The Avengers
Avengers: Age of Ultron
Captain America: Civil War
Ant-Man
Guardians of the Galaxy
X2
Captain America: The Winter Soldier
The Incredible Hulk
X-Men
X-Men: Days of Future Past
Jurassic World
X-Men: The Last Stand
Deadpool
X-Men: First Class
Zathura: A Space Adventure
Man of Steel
Avatar
Captain America: The First Avenger
The Wolverine
Superman II
X-Men Origins: Wolverine
Fantastic Four
Southland Tales
Mad Max: Fury Road
Interstellar
TRON: Legacy
X-Men: Apocalypse